### ISSUE TITLE
pytest failure

### ISSUE THREAD

**Issue by jayvdb** [thombashi/thank-you-stars#2]
Just run `pytest` in the system environment fails as 'thank-you-stars' hasnt been installed.  That can be avoid by creating a `__main__.py` and using `python -m ..`
```py
_______________________________________________________________________________ Test_tys.test_normal[command0-0] _______________________________________________________________________________

self = <test_cli.Test_tys object at 0x7f7756f6a610>, command = ['thank-you-stars', 'pytablewriter', '--dry-run'], expected = 0

    @pytest.mark.parametrize(
        ["command", "expected"],
        [
            [[TYS_CMD, "pytablewriter", DRY_RUN_OPT], 0],
            [[TYS_CMD, "thank-you-stars", CHK_OPT], 0],
            [[TYS_CMD, "thank-you-stars", CHK_OPT, "--include-owner-repo", DEPTH_OPT, 3], 0],
            [[TYS_CMD, "pytablewriter", DRY_RUN_OPT, DEPTH_OPT, -1], errno.EINVAL],
        ],
    )
    def test_normal(self, command, expected):
>       assert SubprocessRunner(command).run() == expected

test/test_cli.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.8/site-packages/subprocrunner/_subprocess_runner.py:133: in run
    self.__verify_command()
/usr/lib/python3.8/site-packages/subprocrunner/_subprocess_runner.py:246: in __verify_command
    Which(base_command).verify()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = command=thank-you-stars, is_exist=False, follow_symlinks=False

    def verify(self) -> None:
        if not self.is_exist():
>           raise CommandError(
                "command not found: '{}'".format(self.command), cmd=self.command, errno=errno.ENOENT
            )
E           subprocrunner.error.CommandError: command not found: 'thank-you-stars'

/usr/lib/python3.8/site-packages/subprocrunner/_which.py:43: CommandError
```

**Comment by jayvdb** [comment]
The tests also require a GitHub token to have been set up first, and it runs `pip show thank-you-stars` which wont work unless the package has been installed first.

**Comment by thombashi** [comment]
Thank you for your feedback.
I would try to loosen the preconditions to execute tests.

**Comment by thombashi** [comment]
@jayvdb 

>The tests also require a GitHub token to have been set up firs

Now, GitHub token becomes optional. You can run tests without a token setup.

>Just run pytest in the system environment fails as 'thank-you-stars' hasnt been installed. That can be avoid by creating a __main__.py and using python -m ..
>it runs pip show thank-you-stars which wont work unless the package has been installed first.

Tests for this project are expected to launch by `tox` and it installs `thank-you-stars` package automatically, so you can assume the package installed at test time.
Did you mean this does not work correctly?

**Comment by jayvdb** [comment]
Sure it is OK, but it does create difficulties.  e.g. when building an RPM, the package is installed into the buildroot, not the normal root, so the bin script is in a directory not in the PATH.  And distros dont like running tox to be able to run the tests.  tox is a dev test tool; not so useful when testing on a predetermined environment with versions of other packages which can not been chosen, and disconnected from the internet.  The best approach is to use `python -m thank_you_starts` as the entry point in the tests; the bin script is then assumed to work correctly.

**Comment by thombashi** [comment]
Thank you for the explanation.

I understand the background, and I applied the followings:

- rename `main.py` to `__main__.py` and change the entry point coincides with it
- change to use `python -m thank_you_starts` for tests
