### ISSUE TITLE
Incompatibility with latest appconfigpy

### ISSUE THREAD

**Issue by jayvdb** [thombashi/thank-you-stars#4]
```
  File "../thank-you-stars/thank_you_stars/_config.py", line 10, in <module>
    app_config_mgr = ConfigManager(
TypeError: __init__() got an unexpected keyword argument 'config_item_list'
```

The argument is now called `config_items`.

Fairly easy to support old and new with exception handling, if that is desirable.

**Comment by thombashi** [comment]
Thank you for your report.
I had fixed the code and update appconfigpy requirement.
